# Generated by Django 4.0 on 2022-01-06 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_genre_episode_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='genre',
        ),
        migrations.AddField(
            model_name='genre',
            name='anime',
            field=models.ManyToManyField(to='main.Anime'),
        ),
    ]
