# Generated by Django 4.0 on 2022-01-06 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_episode_genre_genre_anime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='anime',
        ),
        migrations.AddField(
            model_name='anime',
            name='genre',
            field=models.ManyToManyField(to='main.Genre'),
        ),
    ]
