# Generated by Django 4.0 on 2022-01-06 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_genre_anime_anime_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='season',
            name='id',
        ),
        migrations.AlterField(
            model_name='season',
            name='number',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
